export type userTypes = {
    idx: number;
    userId?: string | null;
    userImage?: string | null;
    userRole: number;
    userEmail: string;
    userName?: string;
    userFirstName?: string;
    userPick?: number;
    userNickName: string;
    userAddress: string;
    userZip: string;
    userAddressMore: string;
    credit: number;
    userStatus: number;
    userBirth: string;
    userPhone: string;
    userWait?: number;
    userType: number;
    profileCheck: number;
    addressCheck: number;
    businessCheck: number;
    userGender: number;
    payType: number;
    businessName: string | null;
    abn: string | null;
    businessType: number;
    paypal: string | null;
    bankNumber: string | null;
    bankName: string | null;
    snsType: number;
};

export type addressListType = {
    idx: number;
    address: string;
    addressMore: string;
    lat: number;
    lot: number;
    main: number;
    moreText: string;
    postcode: null | string;
};
